" === General Setup ===
set nocompatible            " Use Vim settings, rather then Vi settings
syntax enable               " Activate Syntax Highlight
filetype plugin indent on
set encoding=utf-8
set nowrap                  " Deactivate Wrapping
set nrformats=              " Treat all numbers as decimal
set noswapfile              " I don't like Swapfiles
set nojoinspaces            " Insert only one space when joining lines
set hlsearch                " Highlight Search Results
set laststatus=2            " Always show status line
set ttimeout
set ttimeoutlen=100

" Adjust to editor config
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Fuzzy finder without plugins
set path+=**
set wildmenu

" Disable banner in netrw
let g:netrw_banner=0

" Clear the search buffer when hitting return
nnoremap <CR> :nohlsearch<cr>
