export GOPATH=/Users/dbreuer/Code/go
export PATH=.bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/share/npm/bin:${GOPATH//://bin:}/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/dbreuer/.oh-my-zsh"

#ZSH_THEME="dracula"
# ZSH_THEME="muse"
#ZSH_THEME="norm"
#ZSH_THEME="smt"
ZSH_THEME="sorin"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
plugins=(
    brew
    chruby
    docker
    dotenv
    emacs
    iterm2
    git
    history-substring-search
    osx
    rake
    ruby
    tmux
    tmuxinator
    vagrant-prompt
    vagrant
)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# # Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# Manually load syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Still have ponysay
ponysay -o --f walter discord rainbowfly pinkieumbrellahat twilighttime pinkiesilly pinkiefly
echo ""
