export PATH=~/.dotfiles/bin:/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/share/npm/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/dbreuer/.oh-my-zsh"

ZSH_THEME="sorin"

# Configure fzf
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

DISABLE_AUTO_TITLE="true"

zstyle ':omz:plugins:eza' 'icons' yes

# Which plugins would you like to load?
plugins=(
  asdf
  brew
  docker
  docker-compose
  eza
  fzf
  iterm2
  git
  heroku
  history-substring-search
  macos
  rake
  ruby
  tmux
  tmuxinator
  z
)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# # Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# Manually load syntax highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Still have ponysay
ponysay -o --f walter discord rainbowfly pinkieumbrellahat twilighttime pinkiesilly pinkiefly
echo ""
